### ISSUE TITLE
Implement method of accessing metadata from sale entity

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/mesa-subgraph#78] opened 2021-07-28 19:40 UTC
As discussed with Nico the best option for this is to utilise msg.sender (from) on the subgraph side to then lookup the metadata from the launchedTemplate map:

– Using the SaleInitialized event to listen for the new deployed sale contract address (SaleLauncher Level)
– Using the msg.sender from the event to reference the template contract address (Example for msg.sender context: https://github.com/nicoelzer/swapr-subgraph/blob/1adae49a080de0aa17249bd72cc32d6a0dbc096d/src/mappings/core.ts#L116)
– With the temlate contract address we can lookup the metadata on the TemplateLauncher by calling the launchedTemplate mapping that returns the metadata

**Comment by adamazad** [comment] 2021-08-02 11:24
This would be a duplicate of #69 unless you want `metadataContentHash` to be a direct property of `FixedPriceSale`.

**Comment by rossneilson** [comment] 2021-08-02 11:26
The idea was it being a direct property as that makes sense for how the UI is going to consume the data.
How were you planning on linking the template to the sale? currently its not very easy to do

**Closed as completed** 2021-08-03 10:57 UTC
Labels: enhancement
